### ISSUE TITLE
Viewing the player

### ISSUE THREAD

**Issue by jamminjames** [RemcoB00/cordova-phonegap_youtube_player_api_android#2]
In your documentation, you say:

To view the video player use this code and add the YouTube video id:
`window.plugins.youtube.show({
  videoid: "THE_VIDEO"},
  function() {},
  function() {}
);`

Do you simply wrap that in a `<script>` tag? That didn't work for me, but it could be a jquery.mobile issue, as it doesn't like scripts being placed in html pages. But making a .js file and calling it is a problem, because you'd have to have a different file for each video you want to play. How can this be handled?

**Comment by RemcoB00** [comment]
Hey Jammin,
I released today the new version of the plugin that works completely with the latest version of Cordova. I hope this will fix your problem.

You can call the plugin from inline HTML (via onclick) and via a separate js file. See the new [example.html](https://github.com/RemcoB00/cordova-phonegap_youtube_player_api_android/blob/master/example.html) file for a full example of how you can use this plugin.
