### ISSUE TITLE
Closing the player at end of video

### ISSUE THREAD

**Issue by bmcharg** [RemcoB00/cordova-phonegap_youtube_player_api_android#3]
Is there a way - either automatically or programatically - to close the player and return to the app when the end of the video is reached?

**Comment by RemcoB00** [comment]
Unfortunately this isn't possible since the `YouTubeStandalonePlayer` class from YouTube Android Player API doesn't support this. Google needs to implement this functionality first in their API before I can add it to this Cordova / Phonegap plugin.

**Comment by bmcharg** [comment]
Thanks for the quick response!

Gah, that's a pity. I've come across other plugins such as (https://github.com/Glitchbone/CordovaYoutubeVideoPlayer) which support auto-close, but don't seem to work with Android 5.0+ Looks like they use https://code.google.com/p/android-youtube-player/wiki/OpenYouTubePlayerActiviyInstructions rather than the YouTubeStandAlonePlayer. 

As an alternative, is there a way to customise the controls on the end screen, such as to add a close button?

**Comment by RemcoB00** [comment]
It is possible if you build a custom plugin that uses the `YouTubePlayerView` or `YouTubePlayerFragment` class from the YouTube Player API.
